### PR TITLE
Convert PDF to PNG using Streams

### PR DESCRIPTION
**Pull request by TrevorDelaney**
## Description
Created a new end-point "/PdfConverter/StreamToPng" to allow converting PDFs to PNG files using Streams. If there are multiple PNG files to return, they will be put into a ZIP file.

This also fixes an issue with maximum allowed byte size of files being incorrect. Was giving Megabytes max for entered Gigabytes.

### Testing
A REPL was created to help with testing the end-points. This is especially helpful when dealing with file streams in the end points and works as an example of how to make calls to the new end-point.

A DockerFile + Shell script was added to a pipeline folder. Currently, the Shell script can be run to automatically set up a docker container and run the tests in it. This is for integrated/unit tests and has the added benefit of not requiring the developer to have Ghost Script installed directly since it would be downloaded into the docker container. The DockerFile may also be helpful if a Jenkins pipeline is set up for the project because it can automatically run the tests.

### Validation
Like the end-point that takes in bytes, the stream end-point will also validate the given PDF's size to ensure there is data and the PDF is not greater than the maximum available value. The byte[] end-point has the disadvantage that the check only happens after all the byte data has been uploaded. The way the Stream end-point validates the file size is while the file is in the process of being uploaded, so the full file doesn't need to reach the server in order to validate the file is within the size limit.

The resulting PNG file sizes are never validated in either case in code. The PNG files generated from ghost script in some cases can be much larger than the PDF itself. PNG files have to get the full page's pixels, so it is possible to create a 5000 page PDF that is a couple kilobytes until converted to a png.

## Motivation / Context
Issue: https://github.com/TownSuite/TownSuite.IssueTracker/issues/7288
This also fixes issue: https://github.com/TownSuite/TownSuite.IssueTracker/issues/7302
Also fixes: https://github.com/TownSuite/TownSuite.IssueTracker/issues/7311
Also possibly fixes: https://github.com/TownSuite/TownSuite.IssueTracker/issues/7312 (returns Stream instead of byte[])

## Screen shot
An example using the REPL to call the API twice. once for an example of a pdf with multiple pages (created the zip) and another for a pdf with 1 page (created the png):
image

## Follow up
This PR has started getting large, so a follow up PR will be made to clean up the code more:
- Moving the Stream logic in PdfToImageConverter to a new class.
- Add a new class to use in UploadedStreamHandler CopyToAsync method to allow more of the logic to be under test.
- Throw an exception if no PNG files were generated from the PDF. Right now an empty zip may be returned, however the given PDF file is currently validated to ensure it has at least some data in it.
- Possible performance improvements and additional validation.
- Enable the tests using GhostScript to be able to run in Visual Studio and the pipelines .NET build.

### CODE REVIEW

**Comment by TrevorDelaney** [comment]
I'll also look at upgrading the packages mentioned by dependabot in a separate Pull Request.

**Comment by majorsilence** [comment]
> Also possibly fixes: https://github.com/TownSuite/TownSuite.IssueTracker/issues/7312 (returns Stream instead of byte[])

Streams are an acceptable implementation.  Better then byte arrays.

**Review by majorsilence — APPROVED** [review]
👍 

Does the code have the abilty to convert to other image formats other than png?

**Comment by TrevorDelaney** [comment]
> 👍
> 
> Does the code have the abilty to convert to other image formats other than png?

@majorsilence No, both the stream and the byte[] end point seem to only create PNG files. I don't think it would be difficult to implement the option for it to create other files.
The arguments currently given to ghost script in C#: "-sDEVICE=pngalpha -o \"{resultPath}\" -r144 \"{filePath}\" -dNOPAUSE -dBATCH". I think -sDEVICE=pngalpha is currently determining it: https://ghostscript.com/docs/9.54.0/Devices.htm#PNG

**Comment by TrevorDelaney** [comment]
I'll merge this in on Monday. I've checked the build error and it is having an issue with the 3 tests against Ghost Script since there is no executable. I'll fix those in a separate PR.

**Pull request merged**
